name: deployment

on:
  push:
    branches-ignore:
      - main

jobs:
  run-github-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: "development"

      - run: exit 1

      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "failure"
          description: "Failure deploy"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
