name: deploy

on:
  pull_request:
    types: [synchronize, opened, reopened, closed]

env:
  SERVICE: preview-${{ github.event.number }}
  REGISTRY_HOSTNAME: asia.gcr.io
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: asia-northeast1
  IMAGE: app-preview
  APP_ENV: "development"

jobs:
  preview:
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["15.6.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: print PR number
        run: echo "hello-$SERVICE"

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: 335.0.0
          service_account_email: ${{ secrets.GCP_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_ACCOUNT_KEY }}

      - run: gcloud auth configure-docker

      - name: Docker Build
        run: |
          docker build \
            -f Dockerfile \
            --build-arg PREVIEW_ID=$SERVICE \
            -t $REGISTRY_HOSTNAME/$GCP_PROJECT/$IMAGE:$SERVICE .

      - name: Publish
        run: |
          docker push $REGISTRY_HOSTNAME/$GCP_PROJECT/$IMAGE:$SERVICE

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: app-${{ env.SERVICE }}
          image: ${{ env.REGISTRY_HOSTNAME }}/${{ env.GCP_PROJECT }}/${{ env.IMAGE }}:${{ env.SERVICE }}
          region: ${{ env.GCP_REGION }}
          tag: ${{ env.SERVICE }}

      - name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"

  cleanup-preview:
    name: Cleanup the Preview
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: 335.0.0
          service_account_email: ${{ secrets.GCP_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_ACCOUNT_KEY }}

      - run: gcloud auth configure-docker

      - run: |
          gcloud config set project ${PROJECT}
          gcloud config set run/platform managed
          gcloud config set run/region ${REGION}
          gcloud auth configure-docker

      - name: Delete the Cloud Run Service
        run: |
          gcloud --quiet run services delete ${SERVICE} \
            --project ${GCP_PROJECT}
            --region $GCP_REGION \
            --platform managed

      - name: Delete the Docker image in GCR
        run: gcloud container images delete ${REGISTRY_HOSTNAME}/${GCP_PROJECT}/${SERVICE}
